version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: dashboard_medicamentos
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: some
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wordpress-platform
volumes:
  db_data: {}

networks:
  wordpress-platform:
    driver: bridge
